//
//  SectionSS.swift
//  SkeletonNASAApp2
//
//  Created by Fatimah M. Ali on 7/25/17.
//  Copyright © 2017 Fatimah M. Ali. All rights reserved.
//

import UIKit

struct SectionSS
{
    var label: String!
    var photo: UIImage!
    var subtext: String!
    
    static func fetchMyDetails() -> [SectionSS] {
        
        return [
            
            SectionSS(label:"The sun emitted a mid-level solar flare, an M5.6-class, peaking at 3:33 a.m EDT on Aug. 24, 2015. NASA’s Solar Dynamics Observatory, which watches the sun constantly, captured an image of the event. Solar flares are powerful bursts of radiation. Harmful radiation from a flare cannot pass through Earth's atmosphere to physically affect humans on the ground, however -- when intense enough -- they can disturb the atmosphere in the layer where GPS and communications signals travel. Credit: NASA/SDO" , photo: UIImage(named:"ss1.jpg"), subtext: "Figure 1: Sun Releases M5.6-Class Solar Flare. Credit: NASA/SDO."),
            
            SectionSS(label:"It’s small, it’s hot, and it’s shrinking. New NASA-funded research suggests that Mercury is contracting even today, joining Earth as a tectonically active planet. Images obtained by NASA’s MErcury Surface, Space ENvironment, GEochemistry, and Ranging (MESSENGER) spacecraft reveal previously undetected small fault scarps— cliff-like landforms that resemble stair steps. These scarps are small enough that scientists believe they must be geologically young, which means Mercury is still contracting and that Earth is not the only tectonically active planet in our solar system, as previously thought. Managed by the Johns Hopkins University Applied Physics Laboratory in Laurel, Maryland, MESSENGER launched Aug. 3, 2004 and began orbiting Mercury March 18, 2011. The mission ended with a planned impact on the surface of Mercury on April 30, 2015.",  photo: UIImage(named:"ss2.jpg"), subtext: "Figure 2: Tectonically Active Planet Mercury. Image Credit: NASA/JHUAPL/Carnegie Institution of Washington/USGS/Arizona State University"),
            
            SectionSS(label:"The Magellan probe that orbited Venus from 1990 to 1994 was able to peer through the thick Venusian clouds and build up the above image by emitting and re-detecting cloud-penetrating radar. Visible as the bright patch below central North is Venus' highest mountain Maxwell Montes. Other notable features include numerous mountains, coronas, impact craters, tessera, ridges, and lava flows. Although the size and mass of Venus are similar to the Earth, its thick carbon-dioxide atmosphere has trapped heat so efficiently that surface temperature usually exceeds 700 kelvins, hot enough to melt lead." ,  photo: UIImage(named:"ss3.jpg"), subtext: "Figure 3: The North Pole of Venus. Image Credit: SSV, MIPL, Magellan Team, NASA."),
            
            SectionSS(label:"A view of Earth from 36,000 nautical miles away as photographed from the Apollo 10 spacecraft during its trans-lunar journey toward the moon. While the Yucatan Peninsula is obscured by clouds, nearly all of Mexico north of the Isthmus of Tehuantepec can be clearly delineated. The Gulf of California and Baja California and the San Joaquin Valley can be easily identified. Also, the delta of the Rio Grande River and the Texas coast are visible. Note the color differences (greens - east, browns - west) along the 100 degrees meridian.The crew members on Apollo 10 are astronauts Thomas P. Stafford, commander; John W. Young, command module pilot; and Eugene E. Cernan, lunar module pilot. Astronaut Young remained in lunar orbit, in the Command and Service Module (CSM) 'Charlie Brown', while astronauts Stafford and Cernan descended to within nine miles of the lunar surface, in the Lunar Module (LM) 'Snoopy'.",  photo: UIImage(named:"ss4.jpg"), subtext: "Figure 4: May 18, 1969 - Apollo 10 View of the Earth. Image Credit: NASA."),
            
            SectionSS(label:"Much of Mars' surface is covered by fine-grained materials that hide the bedrock, but elsewhere, such as in this scene, the bedrock is well exposed (except where covered by sand dunes). Colors are enhanced in the cutout of a pit exposing reddish layers. This is part of a stereo pair, so check out the stereo anaglyph for a 3D view. This is a stereo pair with ESP_039581_1520. The map is projected here at a scale of 25 centimeters (9.8 inches) per pixel. [The original image scale is 26.7 centimeters (10.5 inches) per pixel (with 1 x 1 binning); objects on the order of 80 centimeters (31.5 inches) across are resolved.] North is up. The University of Arizona, Tucson, operates HiRISE, which was built by Ball Aerospace & Technologies Corp., Boulder, Colo. NASA's Jet Propulsion Laboratory, a division of Caltech in Pasadena, California, manages the Mars Reconnaissance Orbiter Project for NASA's Science Mission Directorate, Washington.",  photo: UIImage(named:"ss5.jpg"), subtext: "Figure 5: Layers and Dark Dunes. Image credit: NASA/JPL-Caltech/Univ. of Arizona"),
            
            SectionSS(label:"NASA’s Juno spacecraft was racing away from Jupiter following its seventh close pass of the planet when JunoCam snapped this image on May 19, 2017, from about 29,100 miles (46,900 kilometers) above the cloud tops. The spacecraft was over 65.9 degrees south latitude, with a lovely view of the south polar region of the planet. This image was processed to enhance color differences, showing the amazing variety in Jupiter’s stormy atmosphere. The result is a surreal world of vibrant color, clarity and contrast. Four of the white oval storms known as the “String of Pearls” are visible near the top of the image. Interestingly, one orange-colored storm can be seen at the belt-zone boundary, while other storms are more of a cream color. JunoCam's raw images are available for the public to peruse and process into image products at: www.missionjuno.swri.edu/junocam. More information about Juno is at: http://www.nasa.gov/juno and http://missionjuno.swri.edu",  photo: UIImage(named:"ss6.jpg"), subtext: "Figure 6: Jupiter’s Clouds of Many Colors. Image Credit: NASA/JPL-Caltech/SwRI/MSSS/Gerald Eichstädt"),
            
            SectionSS(label:"An ethereal, glowing spot appears on Saturn's B ring in this view from NASA's Cassini spacecraft. There is nothing particular about that place in the rings that produces the glowing effect -- instead, it is an example of an 'opposition surge' making that area on the rings appear extra bright. An opposition surge occurs when the sun is directly behind the observer looking toward the rings. The particular geometry of this observation makes the point in the rings appear much, much brighter than would otherwise be expected. For more on the surge, see PIA08247. This view looks toward the sunlit side of the rings from about 28 degrees above the ring plane. The image was taken in visible light with the Cassini wide-angle camera on June 26, 2016. The view was acquired at a distance of approximately 940,000 miles (1.5 million kilometers) from the rings and at a sun-ring-spacecraft, or phase, angle of 0 degrees. Image scale on the rings at center is 56 miles (90 kilometers) per pixel. The Cassini mission is a cooperative project of NASA, ESA (the European Space Agency) and the Italian Space Agency. The Jet Propulsion Laboratory, a division of the California Institute of Technology in Pasadena, manages the mission for NASA's Science Mission Directorate, Washington. The Cassini orbiter and its two onboard cameras were designed, developed and assembled at JPL. The imaging operations center is based at the Space Science Institute in Boulder, Colorado. For more information about the Cassini-Huygens mission visit http://saturn.jpl.nasa.gov and http://www.nasa.gov/cassini. The Cassini imaging team homepage is at http://ciclops.org.",  photo: UIImage(named:"ss7.jpg"), subtext: "Figure 7: Jupiter’s Clouds of Many Colors. Image Credit: NASA/JPL-Caltech/SwRI/MSSS/Gerald Eichstädt"),
            
            SectionSS(label:"This is an image of the planet Uranus taken by the spacecraft Voyager 2. NASA's Voyager 2 spacecraft flew closely past distant Uranus, the seventh planet from the Sun, in January 1986.",  photo: UIImage(named:"ss8.jpg"), subtext: "Figure 8: Image Credit: NASA/JPL"),
            
            SectionSS(label:"New images obtained on May 16, 2016, by NASA's Hubble Space Telescope confirm the presence of a dark vortex in the atmosphere of Neptune. This full visible-light image shows that the dark feature resides near and below a patch of bright clouds in the planet's southern hemisphere. Though similar features were seen during the Voyager 2 flyby of Neptune in 1989 and by the Hubble Space Telescope in 1994, this vortex is the first one observed on Neptune in the 21st century.Neptune's dark vortices are high-pressure systems and are usually accompanied by bright 'companion clouds,' which are also now visible on the distant planet. The bright clouds form when the flow of ambient air is perturbed and diverted upward over the dark vortex, causing gases to likely freeze into methane ice crystals. Full news release and annotated images: Hubble Imagery Confirms New Dark Spot on Neptune",  photo: UIImage(named:"ss9.png"), subtext: "Figure 9: Image Credit: NASA, ESA, and M.H. Wong and J. Tollefson (UC Berkeley)"),
            
            SectionSS(label:"New Horizons scientists made this false color image of Pluto using a technique called principal component analysis to highlight the many subtle color differences between Pluto's distinct regions. The image data were collected by the spacecraft’s Ralph/MVIC color camera on July 14 at 11:11 AM UTC, from a range of 22,000 miles (35,000 kilometers). This image was presented by Will Grundy of the New Horizons’ surface composition team on Nov. 9 at the Division for Planetary Sciences (DPS) meeting of the American Astronomical Society (AAS) in National Harbor, Maryland.",  photo: UIImage(named:"ss10.png"), subtext: "Figure 10: Image Credit: NASA/JHUAPL/SwRI")
        ]
    }
}

