//
//  SectionFirstGalaxies.swift
//  SkeletonNASAApp2
//
//  Created by Fatimah M. Ali on 8/1/17.
//  Copyright © 2017 Fatimah M. Ali. All rights reserved.
//

import Foundation

import UIKit

struct SectionFirstGalaxies
{
    var label: String!
    var photo: UIImage!
    var subtext: String!
    
    static func fetchMyDetails() -> [SectionFirstGalaxies] {
        
        return [
            
            SectionFirstGalaxies(label:"The quest for finding the first galaxies is motivated by at least two main goals: 1) these galaxies are likely the building blocks for present-day galaxies, and 2) they are responsible for making the Universe transparent to light, a period commonly referred to as the reionization epoch. This epoch is one of the most important periods in the history of the universe  because it was when most of the neutral hydrogen in the Universe was evaporated. This event dramatically changed the  Universe forever. Before diving into the method of searching first galaxies, here is a brief summary of what the  Universe was like during the early stage of its lifetime. Immediately after the Big Bang the Universe was too hot and chaotic for electromagnetic radiations to escape. It was only after about 400,000 years that the Universe expanded and cooled enough (to about 3000 Kelvin) for free electrons to be able to combine with protons to form neutral hydrogen. Due to this attraction of electrons to protons, enough empty was created for light to escape and travel to large distances (and eventually reaching us) without bouncing back and forth, for the first time. This is what we see today as the microwave background radiation (light emitted in the microwave part of the electromagnetic spectrum). Even by this time there were no stars and no galaxies in the Universe. The Universe went into the 'Dark ages' during which it was full of neutral hydrogen and we would have to wait until about 100-500 Myrs after the Big Bang for the first stars and first galaxies to form." , photo: UIImage(named:"fgimage1.jpg"), subtext: "Figure 1: Color composite image of the three  newly discovered galaxy candidates at redshift ~7 (at this redshift the age of the universe is merely 800 million years). These galaxies were selected using a medium-band imaging survey called the Fourstar Galaxy Evolution Survey (zFOURGE). For more details about this discovery, please see Tilvi et al 2013."),
            
            SectionFirstGalaxies(label:"The intense radiation from the first stars and galaxies likely ionized the neutral hydrogen and the Universe changed from an opaque to a transparent Universe. This important milestone is referred to as the 'reionization epoch' which most likely occurred between 100 - 1000 Myrs after the Big Bang. Searching for the first galaxies and understanding how and exactly when did this dense fog of neutral hydrogen evaporate are among the frontiers of modern observational cosmology. In order to study the early universe, there are  a few different probes that can be used -- one of them is star-forming galaxies. These galaxies provide a unique probe of the reionization epoch because such galaxies can be observed to very large distances or at very high redshifts -- redshift being a proxy to distance. Astronomers now have some observational evidence that the reionization of the universe occurred somewhere at redshift z > 6 at which the age of the universe was less than one billion years. Identifying galaxies at such large distances (or high redshifts) has been only possible recently due to the advent of near-infrared detectors that are efficient in detecting photons that are highly redshifted due to their extremely large distances in the expanding universe. Taking advantage of redshifts and some other galaxy properties, astronomers have devised a clever way of identifying high-redshift galaxies -- in an expanding Universe, the farther a galaxy is, the more its light shifted in wavelength (towards redder or longer wavelengths)." ,  photo: UIImage(named:"fgimage2.jpg"), subtext: "Figure 2: Lyman-break (dropout) selection method: Due to the presence of neutral hydrogen in the intergalactic-medium, flux shortward (blueward) of the Lyman-break gets attenuated cause a sharp flux-drop. This break shifts towards longer wavelengths for more and more distant galaxies. For redshift~7 galaxies, the flux drops in the z' band while this object is detected in longer wavelength bands(Tilvi et al 2013)."),
            
            SectionFirstGalaxies(label:"One of the popular methods of identifying extremely distant galaxy candidates is to use a technique called Lyman-break selection method  in which galaxies are selected based on strong absorption of galaxy's blue light (light at wavelengths shortward of Lyman-break wavelength) caused due to the presence of neutral hydrogen in the vicinity of the galaxy. This break gets shifted towards longer wavelengths for more distant galaxies. The figure to the right illustrates this technique --- a combination of broad-band filters (middle panel) used to identify z~7 galaxy candidates. The dropout candidate galaxy (top panel) drops out of the z' filter and is visible in all filters that are redward of about 9000Angstrom. The bottom panel shows a filter set consisting of medium-band filters that provide a better spectral resolution compared with broad-band only filter sets." ,  photo: UIImage(named:"fgimage3.jpg"), subtext: "Figure 3: T-dwarf contamination: A T-dwarf template spectrum is overlaid on the medium-band photometry of a candidateT-dwarf. As can be seen, the medium-band photometry nicely traces the absorption features of T-dwarfs thereby helping to minimize the contamination of high-redshift galaxy candidates by dwarfs in the Milky Way (Tilvi et al 2013). "),
            
            SectionFirstGalaxies(label:"Contaminants. While the dropout method described above has been used quite extensively to identify galaxy candidates at relatively large distances, there are other objects (e.g., brown dwarfs within the Milky Way) that can mimic the Lyman-break drop. While such brown dwarfs can normally be identified based on their compact sizes using the excellent resolution of the Wide Field Camera on the Hubble Space Telescope, using only object sizes to distinguish stars can eliminate some genuine galaxy candidates because high redshift galaxies tend to be compact. Fortunately, medium-band filters (filters that allow photons with a smaller wavelength coverage compared with the broad-band filters) provide a great way to identify features that are associated with brown dwarfs. The figure below shows an example of a T-dwarf that mimics a dropout galaxy candidate. As can be seen the absorption features (or drop in the fluxes) are nicely traced by the medium-band filters.",  photo: UIImage(named:"fgimage4.jpg"), subtext: "Figure 4: Artist's conception of a Tdwarf (Credit: V. Tilvi).")
        ]
    }
    
}
